"""
AI Agent.

This module implements the core AI agent responsible for
interacting with the LLM and executing tools.
"""

import json

from src.groq_client import get_client


class Agent:
    """
    AI Agent capable of interacting with the LLM.
    """

    def __init__(
        self,
        tool_registry,
        tool_schemas,
        model,
    ):
        """
        Initialize the AI Agent.

        Args:
            tool_registry:
                Registry containing all available tools.

            tool_schemas:
                Tool schemas exposed to the LLM.

            model:
                LLM model name.
        """

        self.client = get_client()

        self.tool_registry = tool_registry

        self.tool_schemas = tool_schemas

        self.model = model

    def run(self, user_query):
        """
        Process a user query.

        Args:
            user_query:
                User input.

        Returns:
            Final response generated by the LLM.
        """

        messages = [
            {
                "role": "user",
                "content": user_query
            }
        ]

        while True:

            response = self._call_llm(messages)

            choice = response.choices[0]

            assistant_message = choice.message

            finish_reason = choice.finish_reason

            messages.append(assistant_message)

            if finish_reason == "stop":

                return assistant_message.content

            elif finish_reason == "tool_calls":

                tool_messages = self._execute_tools(
                    assistant_message.tool_calls
                )

                messages.extend(tool_messages)

            else:

                raise ValueError(
                    f"Unsupported finish reason: {finish_reason}"
                )

    def _call_llm(self, messages):
        """
        Call the LLM.

        Args:
            messages:
                Conversation messages.

        Returns:
            ChatCompletion response.
        """

        return self.client.chat.completions.create(
            model=self.model,
            messages=messages,
            tools=self.tool_schemas,
            tool_choice="auto"
        )

    def _execute_tool(self, tool_call):
        """
        Execute a single tool.

        Args:
            tool_call:
                Tool requested by the LLM.

        Returns:
            dict:
                Tool execution result.
        """

        tool_name = tool_call.function.name

        tool_arguments = json.loads(
            tool_call.function.arguments
        ) or {}

        tool = self.tool_registry.get(tool_name)

        if tool is None:

            return {
                "success": False,
                "error": f"Tool '{tool_name}' is not registered."
            }

        try:

            tool_result = tool(**tool_arguments)

            return tool_result

        except Exception as error:

            return {
                "success": False,
                "error": str(error)
            }

    def _execute_tools(self, tool_calls):
        """
        Execute multiple tools.

        Args:
            tool_calls:
                List of tool calls.

        Returns:
            List of tool messages.
        """

        tool_messages = []

        for tool_call in tool_calls:

            tool_result = self._execute_tool(
                tool_call
            )

            tool_message = self._build_tool_message(
                tool_call,
                tool_result
            )

            tool_messages.append(tool_message)

        return tool_messages

    def _build_tool_message(
        self,
        tool_call,
        tool_result,
    ):
        """
        Build a tool message for the LLM.

        Args:
            tool_call:
                Original tool call.

            tool_result:
                Tool execution result.

        Returns:
            Tool message.
        """

        return {
            "role": "tool",
            "tool_call_id": tool_call.id,
            "content": json.dumps(tool_result)
        }